def map_to_profile_fields(merged: dict) -> dict:
    return {
        "full_name": merged.get("full_name"),
        "date_of_birth": merged.get("date_of_birth"),
        "gender": merged.get("gender"),
        "religion": merged.get("religion"),
        "caste": merged.get("caste"),
        "mother_tongue": merged.get("mother_tongue"),
        "height": merged.get("height"),
        "blood_group": merged.get("blood_group"),
        "mobile": merged.get("mobile"),
        "email": merged.get("email"),
        "city": merged.get("city"),
        "state": merged.get("state"),
        "education": merged.get("education") or merged.get("highest_education"),
        "occupation": merged.get("occupation"),
        "annual_income": merged.get("annual_income"),
        "father_name": merged.get("father_name"),
        "mother_name": merged.get("mother_name"),
        "siblings": merged.get("siblings"),
        "family_type": merged.get("family_type"),
        "rashi": merged.get("rashi"),
        "nakshatra": merged.get("nakshatra"),
        "gotra": merged.get("gotra"),
        "manglik": merged.get("manglik"),
        "ai_confidence": merged.get("ai_confidence", 0.0),
    }
